# Generated by Django 3.1.5 on 2021-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/samply.jpg', null=True, upload_to=''),
        ),
    ]
